<script lang="ts">
	import { CONTACT_EMAIL, CONTACT_SITE, LEGAL_LAST_UPDATED_EN } from '$lib/legal/meta';
</script>

<!-- English translation. If there is any discrepancy, the Japanese version prevails. -->
<h1>Privacy Policy</h1>
<p class="updated">Last updated: {LEGAL_LAST_UPDATED_EN}</p>

<p>This Privacy Policy (the "Policy") describes how Nagi (the "Service") handles information.</p>
<div class="summary">
	<h2>The short version</h2>
	<ul>
		<li><strong>We never receive your password, and we don't collect your email.</strong></li>
		<li><strong>No advertising, no analytics.</strong> No cookies either.</li>
		<li>
			Your PDS holds the authoritative copy of your posts. Nagi keeps
			<strong>a copy for display and search</strong>.
			<strong>"Kossori" (quiet) posts are the exception: Nagi holds the only copy.</strong>
		</li>
		<li>
			<strong>AI writing is done by a model running on the operator's home server.</strong> Your
			post text and images are never sent to an outside provider. Only when current facts must be
			checked do we send <strong>search queries and the URLs you shared</strong> to Google.
		</li>
		<li><strong>You can delete all of it from Settings at any time.</strong></li>
	</ul>
</div>

<nav class="toc">
	<h2>Contents</h2>
	<ol>
		<li><a href="#p1">Terms used here</a></li>
		<li><a href="#p2">What we store on our servers</a></li>
		<li><a href="#p3">What we do not collect</a></li>
		<li><a href="#p4">How we use information</a></li>
		<li><a href="#p5">AI features and what leaves the Service</a></li>
		<li><a href="#p6">Where data goes outside the Service</a></li>
		<li><a href="#p7">What is stored on your device</a></li>
		<li><a href="#p8">How public your data is</a></li>
		<li><a href="#p9">Retention and deletion</a></li>
		<li><a href="#p10">People under 18</a></li>
		<li><a href="#p11">Changes to this Policy</a></li>
		<li><a href="#p12">Contact</a></li>
		<li><a href="#p13">Governing language</a></li>
	</ol>
</nav>

<h2 id="p1">1. Terms used here</h2>
<p>
	The Service is an AppView running on the AT Protocol.
	<strong>
		The authoritative copy of your posts lives in your own PDS; the Service keeps a copy for display
		and search, plus data derived from it.
	</strong>
	"Kossori" (quiet) posts, and the diaries for days that contain one, are the exception:
	<strong>their only copy lives on the Service's servers</strong> (putting them in a PDS would make them
	readable by anyone). This Policy sets out which information is stored where.
</p>
<ul>
	<li>
		<strong>PDS</strong>: Where your account and records live on the AT Protocol — a provider you
		chose, or a server you run yourself. The operator of the Service does not run it.
	</li>
	<li>
		<strong>Our servers</strong>: The servers the operator runs to provide timelines and search (the
		AppView and Bot-tan's server).
	</li>
	<li><strong>Bot-tan</strong>: The AI-powered character that responds on the Service.</li>
</ul>

<h2 id="p2">2. What we store on our servers</h2>
<p>
	Your PDS holds the authoritative copy of your posts. This section lists what
	<strong>we keep on our own servers</strong> in addition to that.
</p>
<ul>
	<li>
		<strong>Post text and link cards.</strong> A copy, used to render timelines and to search. We do not
		store the attached images themselves — we fetch them from your PDS and relay them each time they are
		displayed.
	</li>
	<li><strong>Reactions, profile, channels, and custom emoji.</strong> Also copies.</li>
	<li>
		<strong>The text of "Kossori" posts, and of the diaries for days that contain one.</strong>
		These are not copies but the <strong>only</strong> copy. They are visible to no one but you and Bot-tan.
		Putting them in a PDS would make them readable by anyone, so we keep them only on our servers — the
		same reasoning as for mute settings and your Home list. In exchange, they are lost if the Service
		shuts down and cannot be taken to another app. Kossori posts made before 18 August 2026 also remain
		in your PDS, as the design at the time required.
	</li>
	<li><strong>Your DID, handle, and PDS URL.</strong></li>
	<li>
		<strong>Semantic vectors.</strong> Derived from your posts and profile, used to power search.
	</li>
	<li>
		<strong>Text generated by Bot-tan.</strong> Replies to you, your analysis, diaries, card comments,
		and anonymous "Affirm together" summaries. A summary is stored with the original post's URI and CID.
		When the original is a Kossori post, that URI is an identifier issued by the Service that contains
		no author DID, so neither the summary nor a reaction to it can be traced back to the author.
	</li>
	<li><strong>Your conversation history with Bot-tan.</strong></li>
	<li><strong>Notifications and read state.</strong></li>
	<li>
		<strong>Push notification destinations.</strong> The endpoint URL and encryption keys, stored only
		if you enable notifications.
	</li>
	<li>
		<strong>Mute settings.</strong> Visible only to you. We keep these on our servers rather than in your
		PDS because records there are readable by anyone, which would make public who you have muted.
	</li>
	<li>
		<strong>Your Home list.</strong> Visible only to you. We keep it on our servers rather than in your
		PDS so the people you add are not made public.
	</li>
	<li>
		<strong>Bookmarks and folders.</strong> We store only folder names and the URIs of bookmarked items
		and the last-used folder ID on our servers, visible only to you. They are not stored in your PDS,
		and we do not create a snapshot of the bookmarked content.
	</li>
	<li>
		<strong>Drafts and synced settings.</strong> For drafts without images, we store text, mentions, channels,
		Bluemoji, link URL/title/description, and quote URI, plus post and translation settings, visible only
		to you. We do not store images, link thumbnails, or other binary data.
	</li>
	<li>
		<strong>“Affirm together” dismissals.</strong> We store dismissed post URIs, visible only to you,
		and delete them when the seven-day candidate period ends.
	</li>
	<li><strong>Translation cache and card collection records.</strong></li>
</ul>
<p>
	As features are added, the information we handle may grow. We will announce significant changes as
	revisions to this Policy.
</p>

<h2 id="p3">3. What we do not collect</h2>
<ul>
	<li><strong>Passwords</strong>: You sign in via OAuth; the operator never receives one.</li>
	<li><strong>Email addresses</strong>: Not needed to sign up, so we do not collect them.</li>
	<li><strong>Payment details, phone numbers, location</strong>: Not collected.</li>
	<li>
		<strong>Advertising or analytics tracking</strong>: The Service carries no advertising and uses
		no analytics tools. It does not use cookies.
	</li>
	<li>
		<strong>IP addresses</strong>: Held briefly in memory to rate-limit excessive access, never
		written to our database. They do appear in our hosting provider's access records (<a href="#p6"
			>Section 6</a
		>).
	</li>
</ul>

<h2 id="p4">4. How we use information</h2>
<ul>
	<li>To provide the Service — timelines, profiles, channels, and search</li>
	<li>
		To provide AI features — Bot-tan's replies, automatic analysis, diaries, card comments, and
		anonymous summaries
	</li>
	<li>To deliver notifications</li>
	<li>To prevent abuse and excessive load</li>
	<li>To investigate faults and improve the Service</li>
</ul>

<h2 id="p5">5. AI features and what leaves the Service</h2>
<p>
	The text produced by the Service's AI features is written by a
	<strong>local AI model that the operator runs at home</strong>. Bot-tan's replies, the automatic
	profile analysis, diaries, card comments, "Affirm together" anonymous summaries, and translations
	are all generated by that model.
</p>
<p>
	<strong>
		Your post text, attached images, profile, and conversation history with Bot-tan are never sent
		to an outside provider in order to generate them.
	</strong>
</p>
<h3>Google is used only to check current facts</h3>
<p>
	Only when current facts are needed — the weather, or whether a work or song actually exists — do
	we use the search capability of the <strong>Gemini API provided by Google LLC (paid tier)</strong
	>. In that case only these two things are sent to Google:
</p>
<h3>Data sent to Google (Gemini API)</h3>
<p>To provide AI features, the following is sent to Google:</p>
<ul>
	<li>
		The <strong>search queries</strong> assembled by the local AI model. They never contain personal names,
		handles, DIDs, conversation history, or Bot-tan's system prompt.
	</li>
	<li>
		The <strong>URLs of links you included in a post</strong> (Google fetches the content at those URLs)
	</li>
</ul>
<p>
	The research comes back to the local AI model, which writes the final wording. The text and images
	of your posts themselves are never passed to Google for this research.
</p>
<h3>How Google handles it (paid-tier terms)</h3>
<ul>
	<li>
		<strong>How OpenAI handles it</strong>: Data submitted through the OpenAI API is not used to
		train or improve OpenAI models unless the API organization explicitly opts in to data sharing.
	</li>
	<li>
		The search queries and the URLs you shared are retained by Google for <strong>30 days</strong>.
	</li>
	<li>
		Logs are retained for <strong>up to 55 days</strong> to detect and prevent policy violations and to
		meet legal obligations. During that period, Google staff may review content flagged as potentially
		violating.
	</li>
	<li>
		Data may be stored or cached transiently in any country where Google or its agents maintain
		facilities.
	</li>
</ul>
<p>
	The Service is limited to people aged 18 or older because the search capability above uses the
	Gemini API, whose terms require it. See Section 2 of the <a href="/terms">Terms of Service</a>.
</p>

<h2 id="p6">6. Where information is sent</h2>
<div class="table-scroll">
	<table>
		<thead>
			<tr>
				<th>Recipient</th>
				<th>Content</th>
			</tr>
		</thead>
		<tbody>
			<tr>
				<td>Google (Gemini API search and link fetching)</td>
				<td>As set out in Section 5 (search queries and shared link URLs only)</td>
			</tr>
			<tr>
				<td>OpenAI (OpenAI Moderation API)</td>
				<td>As set out in Section 5 (Automated content moderation and safety evaluation)</td>
			</tr>
			<tr>
				<td>Your PDS operator</td>
				<td>Login authentication, reading and writing records</td>
			</tr>
			<tr>
				<td>Our hosting provider (Vercel)</td>
				<td>
					Serving the site. As part of that, access records such as IP addresses and browser type
					are retained for a limited period
				</td>
			</tr>
			<tr>
				<td>Your browser's push service (Google, Apple, Mozilla, and so on)</td>
				<td>
					Only if you enable notifications. A notification includes the other person's display name
					and roughly the first 80 characters of the post
				</td>
			</tr>
			<tr>
				<td>Jetstream, plc.directory</td>
				<td>Receiving public records, and resolving DIDs</td>
			</tr>
			<tr>
				<td>Bluesky's public AppView</td>
				<td>The analysis run when you sign up, and posts if you enable crossposting</td>
			</tr>
			<tr>
				<td>External translation services (Kagi, DeepL, Google)</td>
				<td>
					Only when you choose "translate with another service". The site opens with the post text
					in the URL
				</td>
			</tr>
			<tr>
				<td>AI server the operator runs at home</td>
				<td>
					Generating Bot-tan's writing, translating posts, and generating semantic vectors for
					search. Nothing goes to an external provider
				</td>
			</tr>
		</tbody>
	</table>
</div>
<p>
	We do not provide your information to third parties other than the above.
	<strong>We do not provide information to advertising or analytics companies.</strong> This does not
	apply where disclosure is required by law.
</p>
<p>
	Features you opt into also <strong>create additional records in your own PDS.</strong> Bluesky
	crossposting creates <code>app.bsky.feed.post</code>; publishing to standard.site creates
	<code>site.standard.publication</code> and <code>site.standard.document</code>. All of these are
	public records, and you are asked to authorize them when you turn the feature on. Editing or
	deleting a post on Nagi updates or removes the matching record, and deleting all of your data from
	Settings removes them as well.
</p>

<h2 id="p7">7. What is stored on your device</h2>
<p>
	The Service stores the following in your browser. For signed-out post replies and card draws, only
	the information described below is sent to our servers.
</p>
<ul>
	<li>
		<strong>Local storage</strong>: The DID you are signed in as, theme, display language,
		OAuth-related crosspost settings, local caches of synced data, your consent state for signed-out
		AI use, and a random device value and today’s card for signed-out card draws
	</li>
	<li>
		<strong>IndexedDB</strong>: Your OAuth session, legacy device drafts with images that have not
		migrated, and your signed-out “Private on this device” posts and Bot-tan replies
	</li>
</ul>
<p>
	The Service does not use cookies. These are cleared when you sign out or clear your browser data.
</p>
<p>
	Signed-out “Private on this device” posts are not used for public posts, search, “Affirm
	together,” profiles, or automatic analysis. Their text is sent to a short-lived processing area
	only to generate Bot-tan’s reply. It is deleted as soon as your device receives the reply, and
	within 24 hours if delivery does not complete. Section 5 describes handling by the AI provider.
</p>
<p>
	When you draw an Affirmation Card while signed out, the Service sends a random device value to the
	server. The server stores its hash, that day’s card number, and an expiry at the card-day boundary
	to prevent duplicate draws on the same device. If you sign in during that card day, the draw is
	linked to your DID and added to your Card File. The local result is deleted after the boundary,
	and earlier days are not imported later.
</p>

<h2 id="p8">8. How public your data is</h2>
<ul>
	<li>
		Posts, reactions, and profiles on the Service are public AT Protocol records. Nagi's interface
		and AppView do not show third parties who reacted or another person's reaction history. However,
		these public records can still be fetched directly from a PDS or displayed by applications other
		than the Service.
	</li>
	<li>Mute settings are visible only to you. The person you muted is not notified.</li>
	<li>Your Home list is visible only to you. People you add are not notified.</li>
</ul>
<div class="callout warn">
	<p>
		<strong>"Kossori" (quiet) posts are readable only by you and Bot-tan.</strong> Their text is
		stored on our servers rather than in your PDS, and never appears in shared timelines, search,
		threads, or anyone else's profile. Only you and Bot-tan can reply.
		<strong>A diary for a day that contains a Kossori post is treated the same way</strong>: other
		users see only the date and the post count (the cell in the annual graph on your profile).
	</p>
	<p>
		However, <strong
			>an anonymous Bot-tan summary — with neither your name nor the original wording — may appear
			in "Affirm together."</strong
		> The original-post URI stored alongside that summary is an identifier issued by the Service that
		contains no author DID. Readers can react to the summary, but cannot trace it back to you or to the
		original text. Channel-only posts may be summarized in the same way, but they are stored in your PDS
		as ordinary public records.
	</p>
	<p>
		<strong>Kossori posts made before 18 August 2026 remain in your PDS as public records.</strong> The
		Service shows them only to you, but anyone reading your PDS directly can fetch them.
	</p>
</div>

<h2 id="p9">9. Retention and deletion</h2>
<div class="callout">
	<p>
		From "Delete data" in Settings, you can
		<strong>delete all of your data described in this Policy from our servers.</strong> This cannot be
		undone.
	</p>
</div>

<h3>What is deleted</h3>
<ul>
	<li>Copies of your posts, reactions, profile, and channels</li>
	<li>
		<strong>The text of "Kossori" posts and of the diaries containing them.</strong> These have no counterpart
		in any PDS, so this removes them completely.
	</li>
	<li>Nagi post, reaction, and profile records in your PDS</li>
	<li>Custom emoji in your PDS that have a marker showing they were created by Nagi</li>
	<li>Semantic vectors used for search</li>
	<li>AI-generated analysis, diaries, card comments, and anonymous summaries</li>
	<li>Your conversation history with Bot-tan</li>
	<li>
		Notifications, push notification destinations, mute settings, your Home list, bookmarks, and
		folders
	</li>
	<li>
		Channel subscriptions (both yours, and records of other people subscribing to your channels)
	</li>
</ul>
<p>We also delete entries where another user had added you to their Home.</p>

<h3>What is not deleted</h3>
<ul>
	<li>
		<strong>Your visit history and gifts in Bot-tan's Room, and your Discord link.</strong> These belong
		to Bot-tan's Room and community, not to Nagi. They are deliberately left alone so you can keep using
		them after leaving Nagi. If you want them removed, please ask through each of those services.
	</li>
	<li>
		<strong>Other records in your PDS.</strong> This includes Bluemoji created by other apps and Bluemoji
		registered before Nagi introduced creation markers, and Kossori posts made before 18 August 2026,
		which are public records in your PDS (Kossori posts made since then are not in any PDS, so they do
		not apply). To remove them completely, you must delete them from your PDS yourself.
	</li>
	<li>Logs Google keeps for abuse detection (deleted within 55 days).</li>
	<li>
		Copies of public records fetched or cached by other AppViews or search engines. These are
		outside the operator's control.
	</li>
</ul>
<p>
	Reactions by other users that used your custom emoji remain as those users' data. After the
	Service's copy of the emoji is deleted, its fallback name is displayed instead of the image.
</p>
<p>
	We keep a record of how often features are used for statistical purposes; when you delete your
	data, we unlink those records from your DID.
</p>

<h2 id="p10">10. People under 18</h2>
<p>
	The Service is for people aged 18 or older, and we do not knowingly collect information from
	anyone under 18. If we learn that information from someone under 18 is held, we will delete it
	promptly.
</p>

<h2 id="p11">11. Changes to this Policy</h2>
<p>
	This Policy may change. Where a change materially affects what information we handle or where it
	is sent, we will announce it on the Service.
</p>

<h2 id="p12">12. Contact</h2>
<p>
	For questions about this Policy, or requests about how your data is handled, please use the
	following:
</p>
<ul>
	<li>Email: <a href="mailto:{CONTACT_EMAIL}">{CONTACT_EMAIL}</a></li>
	<li>
		Site: <a href={CONTACT_SITE} target="_blank" rel="noreferrer noopener">{CONTACT_SITE}</a>
	</li>
</ul>

<h2 id="p13">13. Governing language</h2>
<p>
	This English text is provided for convenience. If there is any discrepancy between the Japanese
	and English versions, the original Japanese version prevails.
</p>
