<script lang="ts">
	import { CONTACT_EMAIL, CONTACT_SITE, LEGAL_LAST_UPDATED_EN } from '$lib/legal/meta';
</script>

<!-- English translation. If there is any discrepancy, the Japanese version prevails. -->
<h1>Privacy Policy</h1>
<p class="updated">Last updated: {LEGAL_LAST_UPDATED_EN}</p>

<p>
	This Privacy Policy (the "Policy") describes how Nagi (the "Service") handles information.
</p>
<div class="summary">
	<h2>The short version</h2>
	<ul>
		<li><strong>We never receive your password, and we don't collect your email.</strong></li>
		<li><strong>No advertising, no analytics.</strong> No cookies either.</li>
		<li>
			Your PDS holds the authoritative copy of your posts. Nagi keeps
			<strong>a copy for display and search</strong>.
		</li>
		<li>
			<strong>AI features send your post text and images to Google.</strong> They are not used for training.
		</li>
		<li><strong>You can delete all of it from Settings at any time.</strong></li>
	</ul>
</div>

<nav class="toc">
	<h2>Contents</h2>
	<ol>
		<li><a href="#p1">Terms used here</a></li>
		<li><a href="#p2">What we store on our servers</a></li>
		<li><a href="#p3">What we do not collect</a></li>
		<li><a href="#p4">How we use information</a></li>
		<li><a href="#p5">AI features and what is sent to Google</a></li>
		<li><a href="#p6">Where data goes outside the Service</a></li>
		<li><a href="#p7">What is stored on your device</a></li>
		<li><a href="#p8">How public your data is</a></li>
		<li><a href="#p9">Retention and deletion</a></li>
		<li><a href="#p10">People under 18</a></li>
		<li><a href="#p11">Changes to this Policy</a></li>
		<li><a href="#p12">Contact</a></li>
		<li><a href="#p13">Governing language</a></li>
	</ol>
</nav>

<h2 id="p1">1. Terms used here</h2>
<p>
	The Service is an AppView running on the AT Protocol.
	<strong>
		The authoritative copy of your posts lives in your own PDS; the Service keeps a copy for display
		and search, plus data derived from it.
	</strong> This Policy sets out which information is stored where.
</p>
<ul>
	<li>
		<strong>PDS</strong>: Where your account and records live on the AT Protocol — a provider you
		chose, or a server you run yourself. The operator of the Service does not run it.
	</li>
	<li>
		<strong>Our servers</strong>: The servers the operator runs to provide timelines and search (the
		AppView and Bot-tan's server).
	</li>
	<li><strong>Bot-tan</strong>: The AI-powered character that responds on the Service.</li>
</ul>

<h2 id="p2">2. What we store on our servers</h2>
<p>
	Your PDS holds the authoritative copy of your posts. This section lists what
	<strong>we keep on our own servers</strong> in addition to that.
</p>
<ul>
	<li>
		<strong>Post text and link cards.</strong> A copy, used to render timelines and to search. We do not
		store the attached images themselves — we fetch them from your PDS and relay them each time they are
		displayed.
	</li>
	<li><strong>Reactions, profile, channels, and custom emoji.</strong> Also copies.</li>
	<li><strong>Your DID, handle, and PDS URL.</strong></li>
	<li>
		<strong>Semantic vectors.</strong> Derived from your posts and profile, used to power search.
	</li>
	<li>
		<strong>Text generated by Bot-tan.</strong> Replies to you, your analysis, diaries, and card comments.
	</li>
	<li><strong>Your conversation history with Bot-tan.</strong></li>
	<li><strong>Notifications and read state.</strong></li>
	<li>
		<strong>Push notification destinations.</strong> The endpoint URL and encryption keys, stored only
		if you enable notifications.
	</li>
	<li>
		<strong>Mute settings.</strong> Visible only to you. We keep these on our servers rather than in your
		PDS because records there are readable by anyone, which would make public who you have muted.
	</li>
	<li><strong>Translation cache and card collection records.</strong></li>
</ul>
<p>
	As features are added, the information we handle may grow. We will announce significant changes as
	revisions to this Policy.
</p>

<h2 id="p3">3. What we do not collect</h2>
<ul>
	<li><strong>Passwords</strong>: You sign in via OAuth; the operator never receives one.</li>
	<li><strong>Email addresses</strong>: Not needed to sign up, so we do not collect them.</li>
	<li><strong>Payment details, phone numbers, location</strong>: Not collected.</li>
	<li>
		<strong>Advertising or analytics tracking</strong>: The Service carries no advertising and uses no
		analytics tools. It does not use cookies.
	</li>
	<li>
		<strong>IP addresses</strong>: Held briefly in memory to rate-limit excessive access, never
		written to our database. They do appear in our hosting provider's access records
		(<a href="#p6">Section 6</a>).
	</li>
</ul>

<h2 id="p4">4. How we use information</h2>
<ul>
	<li>To provide the Service — timelines, profiles, channels, and search</li>
	<li>
		To provide AI features — Bot-tan's replies, automatic analysis, diaries, and card comments
	</li>
	<li>To deliver notifications</li>
	<li>To prevent abuse and excessive load</li>
	<li>To investigate faults and improve the Service</li>
</ul>

<h2 id="p5">5. AI features and what is sent to Google</h2>
<p>
	The Service's AI features use the <strong>Gemini API provided by Google LLC (paid tier)</strong>.
	To provide them, the following is sent to Google:
</p>
<ul>
	<li>The text of your posts and any attached images</li>
	<li>Your profile display name and bio</li>
	<li>
		As context for a reply, your earlier posts and related public posts from other users
	</li>
	<li>Your conversation history with Bot-tan</li>
	<li>Links contained in your posts (Google fetches the content at those URLs)</li>
	<li>
		For the automatic profile analysis, up to 100 of your posts and up to 100 posts you reacted to.
		<strong>
			When you first sign up, up to 100 of your Bluesky posts and 100 of your Bluesky likes are used
			instead.
		</strong>
	</li>
</ul>
<h3>How Google handles it (paid-tier terms)</h3>
<ul>
	<li>
		<strong>
			Google does not use the inputs or the generated outputs to improve or train its products or AI
			models.
		</strong>
	</li>
	<li>
		Logs are retained for <strong>up to 55 days</strong> to detect and prevent policy violations and to
		meet legal obligations. During that period, Google staff may review content flagged as potentially
		violating.
	</li>
	<li>
		Data may be stored or cached transiently in any country where Google or its agents maintain
		facilities.
	</li>
</ul>
<p>
	Bot-tan's responses and news selection also use Google Search grounding. In that case the search
	queries and the URLs you shared are passed to Google and retained for 30 days.
</p>
<p>
	The Service is limited to people aged 18 or older because the Gemini API terms require it. See
	Section 2 of the <a href="/terms">Terms of Service</a>.
</p>

<h2 id="p6">6. Where data goes outside the Service</h2>
<div class="table-scroll">
	<table>
		<thead>
			<tr>
				<th>Recipient</th>
				<th>What is sent</th>
			</tr>
		</thead>
		<tbody>
			<tr>
				<td>Google (Gemini API, Google Search grounding)</td>
				<td>As set out in Section 5</td>
			</tr>
			<tr>
				<td>Your PDS provider</td>
				<td>Sign-in, and reading and writing records</td>
			</tr>
			<tr>
				<td>Our hosting provider (Vercel)</td>
				<td>
					Serving the site. As part of that, access records such as IP addresses and browser type are
					retained for a limited period
				</td>
			</tr>
			<tr>
				<td>Your browser's push service (Google, Apple, Mozilla, and so on)</td>
				<td>
					Only if you enable notifications. A notification includes the other person's display name
					and roughly the first 80 characters of the post
				</td>
			</tr>
			<tr>
				<td>Jetstream, plc.directory</td>
				<td>Receiving public records, and resolving DIDs</td>
			</tr>
			<tr>
				<td>Bluesky's public AppView</td>
				<td>The analysis run when you sign up, and posts if you enable crossposting</td>
			</tr>
			<tr>
				<td>External translation services (Kagi, DeepL, Google)</td>
				<td>
					Only when you choose "translate with another service". The site opens with the post text in
					the URL
				</td>
			</tr>
			<tr>
				<td>AI server run by the operator</td>
				<td>
					Generating semantic vectors for search, and translating posts. Nothing goes to an external
					provider
				</td>
			</tr>
		</tbody>
	</table>
</div>
<p>
	We do not provide your information to third parties other than the above.
	<strong>We do not provide information to advertising or analytics companies.</strong> This does not
	apply where disclosure is required by law.
</p>

<h2 id="p7">7. What is stored on your device</h2>
<p>The Service stores the following in your browser. It is not sent to our servers.</p>
<ul>
	<li>
		<strong>Local storage</strong>: The DID you are signed in as, theme, display language,
		translation settings, crosspost settings, frequently used emoji, and unread positions in
		timelines
	</li>
	<li><strong>IndexedDB</strong>: Your OAuth session, and post drafts</li>
</ul>
<p>
	The Service does not use cookies. These are cleared when you sign out or clear your browser data.
</p>

<h2 id="p8">8. How public your data is</h2>
<ul>
	<li>
		Posts, reactions, and profiles on the Service are public AT Protocol records. Applications other
		than the Service can fetch and display them.
	</li>
	<li>Mute settings are visible only to you. The person you muted is not notified.</li>
</ul>
<div class="callout warn">
	<p>
		<strong>"Kossori" (quiet) posts are not private.</strong> They are hidden from the Service's timelines,
		but they are stored in your PDS as ordinary public records, and their text is stored on our servers
		too. Please do not post anything you need to keep secret.
	</p>
</div>

<h2 id="p9">9. Retention and deletion</h2>
<div class="callout">
	<p>
		From "Delete data" in Settings, you can
		<strong>delete all of your data described in this Policy from our servers.</strong> This cannot be
		undone.
	</p>
</div>

<h3>What is deleted</h3>
<ul>
	<li>Copies of your posts, reactions, profile, and channels</li>
	<li>Semantic vectors used for search</li>
	<li>AI-generated analysis, diaries, and card comments</li>
	<li>Your conversation history with Bot-tan</li>
	<li>Notifications, push notification destinations, and mute settings</li>
</ul>

<h3>What is not deleted</h3>
<ul>
	<li>
		<strong>Records in your PDS.</strong> The Service cannot delete them. To remove them completely you
		must delete them from your PDS yourself.
	</li>
	<li>Logs Google keeps for abuse detection (deleted within 55 days).</li>
	<li>
		Copies of public records fetched or cached by other AppViews or search engines. These are outside
		the operator's control.
	</li>
</ul>
<p>
	We keep a record of how often features are used for statistical purposes; when you delete your
	data, we unlink those records from your DID.
</p>

<h2 id="p10">10. People under 18</h2>
<p>
	The Service is for people aged 18 or older, and we do not knowingly collect information from anyone
	under 18. If we learn that information from someone under 18 is held, we will delete it promptly.
</p>

<h2 id="p11">11. Changes to this Policy</h2>
<p>
	This Policy may change. Where a change materially affects what information we handle or where it is
	sent, we will announce it on the Service.
</p>

<h2 id="p12">12. Contact</h2>
<p>
	For questions about this Policy, or requests about how your data is handled, please use the
	following:
</p>
<ul>
	<li>Email: <a href="mailto:{CONTACT_EMAIL}">{CONTACT_EMAIL}</a></li>
	<li>
		Site: <a href={CONTACT_SITE} target="_blank" rel="noreferrer noopener">{CONTACT_SITE}</a>
	</li>
</ul>

<h2 id="p13">13. Governing language</h2>
<p>
	This English text is provided for convenience. If there is any discrepancy between the Japanese and
	English versions, the original Japanese version prevails.
</p>
