/**
 * モデレーションラベルの定義と判定。
 *
 * ラベルの出所はAppViewだけ。公開ATプロトコルラベラーは廃止したので、
 * `src` で発行者を絞る処理も、ラベラーDIDのハードコードも持たない。
 */

export interface SelfLabelOption {
	value: string;
	name: { ja: string; en: string };
	description: { ja: string; en: string };
	badgeText: { ja: string; en: string };
}

/**
 * 投稿作成時にユーザーが指定可能なセルフラベル一覧
 */
export const AVAILABLE_SELF_LABELS: SelfLabelOption[] = [
	{
		value: 'sexual',
		name: { ja: '性的 / NSFW', en: 'Adult / NSFW' },
		description: {
			ja: '成人向けまたは性的な表現を含みます（閲覧時に画像をぼかします）',
			en: 'Contains adult or sexually suggestive content (blurs media)',
		},
		badgeText: { ja: '🔞 性的コンテンツ', en: '🔞 Adult / NSFW' },
	},
	{
		value: 'graphic-media',
		name: { ja: '暴力的・グロテスク', en: 'Graphic Media' },
		description: {
			ja: '流血や暴力などショッキングな表現を含みます（閲覧時に画像をぼかします）',
			en: 'Contains violent or disturbing content (blurs media)',
		},
		badgeText: { ja: '⚠️ 閲覧注意（暴力）', en: '⚠️ Graphic Media' },
	},
	{
		value: 'ai-generated',
		name: { ja: 'AI生成', en: 'AI Generated' },
		description: {
			ja: '画像生成AI等のツールで生成されたコンテンツであることを示します',
			en: 'Indicates content generated by AI tools',
		},
		badgeText: { ja: '🤖 AI生成', en: '🤖 AI Generated' },
	},
];

/**
 * メディアをぼかす対象のラベル。
 * サーバが未成年へ丸ごと出さないラベル（ADULT_LABELS）と同じ集合にしてある。
 */
const BLURRING_LABELS = ['sexual', 'porn', 'nudity', 'graphic-media', '!hide'];

export interface LabelInfo {
	val: string;
	/** 投稿者自身が付けたか（true）、自動判定が付けたか（false）。 */
	isSelfLabel: boolean;
}

/** 表示に使うラベルを、AppViewが返した2つの配列からまとめる。 */
export function extractPostLabels(post: {
	selfLabels?: string[];
	moderationLabels?: string[];
}): LabelInfo[] {
	const labels: LabelInfo[] = [];
	for (const val of post?.selfLabels ?? [])
		if (typeof val === 'string') labels.push({ val, isSelfLabel: true });
	for (const val of post?.moderationLabels ?? [])
		if (typeof val === 'string') labels.push({ val, isSelfLabel: false });
	return labels;
}

/**
 * 画像・メディアをぼかす（Blur）対象か判定
 */
export function shouldBlurMedia(labels: LabelInfo[] | { val: string }[]): {
	shouldBlur: boolean;
	labelName?: string;
} {
	for (const label of labels) {
		if (BLURRING_LABELS.includes(label.val)) {
			const match = AVAILABLE_SELF_LABELS.find((l) => l.value === label.val);
			return {
				shouldBlur: true,
				labelName: match ? match.badgeText.ja : label.val,
			};
		}
	}
	return { shouldBlur: false };
}
