/**
 * AT Protocol / nagi_amateras モデレーションラベル定義および判定ユーティリティ
 */

export const AMATERAS_LABELER_DID = 'did:plc:gvlryvidmd4yju24sdqi5rao';

export interface SelfLabelOption {
	value: string;
	name: { ja: string; en: string };
	description: { ja: string; en: string };
	badgeText: { ja: string; en: string };
}

/**
 * 投稿作成時にユーザーが指定可能なセルフラベル一覧
 */
export const AVAILABLE_SELF_LABELS: SelfLabelOption[] = [
	{
		value: 'sexual',
		name: { ja: '性的 / NSFW', en: 'Adult / NSFW' },
		description: {
			ja: '成人向けまたは性的な表現を含みます（閲覧時に画像をぼかします）',
			en: 'Contains adult or sexually suggestive content (blurs media)',
		},
		badgeText: { ja: '🔞 性的コンテンツ', en: '🔞 Adult / NSFW' },
	},
	{
		value: 'graphic-media',
		name: { ja: '暴力的・グロテスク', en: 'Graphic Media' },
		description: {
			ja: '流血や暴力などショッキングな表現を含みます（閲覧時に画像をぼかします）',
			en: 'Contains violent or disturbing content (blurs media)',
		},
		badgeText: { ja: '⚠️ 閲覧注意（暴力）', en: '⚠️ Graphic Media' },
	},
	{
		value: 'ai-generated',
		name: { ja: 'AI生成', en: 'AI Generated' },
		description: {
			ja: '画像生成AI等のツールで生成されたコンテンツであることを示します',
			en: 'Indicates content generated by AI tools',
		},
		badgeText: { ja: '🤖 AI生成', en: '🤖 AI Generated' },
	},
];

/**
 * 投稿データまたは画像からラベルを判定する
 */
export interface LabelInfo {
	val: string;
	src?: string;
	isSelfLabel?: boolean;
}

export function extractPostLabels(post: any): LabelInfo[] {
	const labels: LabelInfo[] = [];

	// 1. AppViewが検証して返すセルフラベル
	if (Array.isArray(post?.selfLabels)) {
		for (const val of post.selfLabels) {
			if (typeof val === 'string') labels.push({ val, isSelfLabel: true });
		}
	} else if (post?.record?.labels?.values && Array.isArray(post.record.labels.values)) {
		// 旧fixture/外部PostViewとの互換経路。
		for (const item of post.record.labels.values)
			if (item?.val) labels.push({ val: item.val, isSelfLabel: true });
	}

	// 2. AppViewがAmaterasの現在CIDについて検証したラベル
	if (Array.isArray(post?.moderationLabels)) {
		for (const val of post.moderationLabels) {
			if (typeof val === 'string')
				labels.push({ val, src: AMATERAS_LABELER_DID, isSelfLabel: false });
		}
	} else if (Array.isArray(post?.labels)) {
		// 公式PostView互換。ただしAmateras以外のラベルはNagiの設定へ混ぜない。
		for (const item of post.labels) {
			if (item?.val && !item.neg && item.src === AMATERAS_LABELER_DID) {
				labels.push({ val: item.val, src: item.src, isSelfLabel: false });
			}
		}
	}

	return labels;
}

/**
 * 画像・メディアをぼかす（Blur）対象か判定
 */
export function shouldBlurMedia(labels: LabelInfo[]): { shouldBlur: boolean; labelName?: string } {
	for (const label of labels) {
		if (['sexual', 'porn', 'nudity', 'graphic-media', '!hide'].includes(label.val)) {
			const match = AVAILABLE_SELF_LABELS.find((l) => l.value === label.val);
			return {
				shouldBlur: true,
				labelName: match ? match.badgeText.ja : label.val,
			};
		}
	}
	return { shouldBlur: false };
}
