<script lang="ts">
	import { i18n } from '$lib/i18n/i18n.svelte';
</script>

<section class="card prose">
	{#if i18n.locale === 'ja'}
		<h1>利用規約</h1>
		<p class="updated">最終更新日: 2026年7月19日（ドラフト）</p>
		<p>
			この利用規約（以下「本規約」）は、Nagi（以下「本サービス」）の利用条件を定めるものです。本サービスを利用することで、本規約に同意したものとみなされます。
		</p>
		<h2>1. サービスの内容</h2>
		<p>
			本サービスは、AT
			Protocol上で動作するソーシャルネットワークです。投稿はご自身のアカウント（PDS）に保存され、公開タイムラインは誰でも閲覧できます。
		</p>
		<h2>2. 禁止事項</h2>
		<ul>
			<li>法令または公序良俗に違反する行為</li>
			<li>他者への誹謗中傷、嫌がらせ、差別的な発言</li>
			<li>本サービスの運営を妨げる行為</li>
		</ul>
		<h2>3. Botたんの返信について</h2>
		<p>
			本サービスの投稿には、AIによる自動返信（全肯定botたん）が行われることがあります。返信内容はAIが生成したものであり、正確性や適切性を保証するものではありません。
		</p>
		<h2>4. 免責事項</h2>
		<p>
			本サービスは現状有姿で提供され、明示または黙示を問わずいかなる保証も行いません。本サービスの利用により生じた損害について、運営者は責任を負いません。
		</p>
		<h2>5. 規約の変更</h2>
		<p>本規約は予告なく変更されることがあります。変更後の利用継続をもって同意とみなします。</p>
	{:else}
		<!-- English draft translation, pending human review. The Japanese version prevails. -->
		<h1>Terms of Service</h1>
		<p class="updated">Last updated: July 19, 2026 (draft)</p>
		<p>
			These Terms of Service (the "Terms") set out the conditions for using Nagi (the "Service"). By
			using the Service, you are deemed to have agreed to these Terms.
		</p>
		<h2>1. The Service</h2>
		<p>
			The Service is a social network running on the AT Protocol. Your posts are stored in your own
			account (PDS), and the public timeline can be viewed by anyone.
		</p>
		<h2>2. Prohibited conduct</h2>
		<ul>
			<li>Acts that violate laws or public order and morals</li>
			<li>Defamation, harassment, or discriminatory remarks against others</li>
			<li>Acts that interfere with the operation of the Service</li>
		</ul>
		<h2>3. About Bot-tan's replies</h2>
		<p>
			Posts on the Service may receive automatic AI-generated replies (from the fully affirming
			Bot-tan). Replies are generated by AI, and their accuracy or appropriateness is not
			guaranteed.
		</p>
		<h2>4. Disclaimer</h2>
		<p>
			The Service is provided "as is", without warranty of any kind, express or implied. The
			operator accepts no liability for damages arising from use of the Service.
		</p>
		<h2>5. Changes to these Terms</h2>
		<p>
			These Terms may be changed without notice. Continued use of the Service after a change
			constitutes acceptance.
		</p>
		<h2>6. Governing language</h2>
		<p>
			This English text is provided for convenience. If there is any discrepancy between the
			Japanese and English versions, the original Japanese version prevails.
		</p>
	{/if}
</section>
